# -*- coding: utf-8 -*-
"""E-Commerce Customer Behavior and Sales Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yMw_a27GUx6cfOs-nzZlnYqszR2PU7rp

#E-Commerce Customer Behavior and Sales Analysis
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/E_Commerce_Dataset (1).csv')

df.head(4)

df.info()

df.shape

df.isnull().sum()

df=df.drop(columns=['Unnamed: 20'])

df['Date']=pd.to_datetime(df['Date'],format='%d-%m-%Y')

df['Discount_Percentage']=df['Discount_Percentage'].str.replace('%','').astype(float) / 100

df['Discount sales']

df.info()

print("--- Age Distribution ---")
print(df['Age'].describe())

print("\n--- Gender Distribution ---")
print(df['Gender'].value_counts())

print("\n--- Top 5 Cities by Customer Count ---")
print(df['City'].value_counts().head(5))

df.head(1)

df['TotalPrice']=df['Unit_Price']*df['Quantity']*(1-df['Discount_Percentage'])
print('Calculated "TotalPrice" for each item. Displaying the first 5 rows with the new column:')
df.head(2)

df['Month']=df['Date'].dt.month_name()
df['Day_Name']=df['Date'].dt.day_name()
df['Age_Group']=pd.cut(df['Age'],bins=[10,25,35,45,60,80],labels=['10-25','26-35','36-45','46-60','61+'])

df['Total sales'].sum()-df['TotalPrice'].sum(),df['Total sales'].sum(),df['TotalPrice'].sum()

TOP_5_TS=df.groupby(df['Product_Category'],as_index=False)['Total sales'].sum().sort_values(by='Total sales',ascending=False).head(5)
print('Top 5 Product Categories by Total Sales:\n',TOP_5_TS)

plt.figure(figsize=(10,7))
SPTS=sns.barplot(data=TOP_5_TS,x=TOP_5_TS['Product_Category'],y=TOP_5_TS['Total sales'],hue='Product_Category',palette='viridis',legend=False)
plt.title('Top 5 Selling Products by Total sales')
plt.xlabel('Product Category')
plt.ylabel('Total Sales')
#plt.xticks(rotation=45)
for container in SPTS.containers:SPTS.bar_label(container,fmt='%.0f')
plt.show()

TOP_5_QS=df.groupby(df['Product_Category'],as_index=False)['Quantity'].sum().sort_values(by='Quantity',ascending=False).head(5)
print('Top 5 Product Categories by Quantity Sold:\n',TOP_5_QS)

plt.figure(figsize=(10,7))
SPQ=sns.barplot(data=TOP_5_QS,x=TOP_5_QS['Product_Category'],y=TOP_5_QS['Quantity'],hue='Product_Category',palette='viridis',legend=False)
plt.title('Top 5 Selling Products by Quantity')
plt.xlabel('Product Category')
plt.ylabel('Total Quantity Sold')
#plt.xticks(rotation=45)
for container in SPQ.containers:SPQ.bar_label(container)
plt.show()

TOP_10_CS=df.groupby(df['Customer_ID'],as_index=False)['Total sales'].sum().sort_values(by='Total sales',ascending=False).head(10)
print('Top 10 Customers by Spending:\n',TOP_10_CS)

plt.figure(figsize=(10,6))
TCS=sns.barplot(data=TOP_10_CS,x=TOP_10_CS['Customer_ID'],y=TOP_10_CS['Total sales'],hue='Customer_ID',palette='magma',legend=False)
plt.title('Top 10 Customers by Spending')
plt.xlabel('Customer ID')
plt.ylabel('Total Spending')
plt.xticks(rotation=45)
for container in TCS.containers:TCS.bar_label(container)
plt.show()

#Payment Method Distribution by Total Sales
PMD=df.groupby(['Payment_Method'],as_index=False)['Total sales'].sum().sort_values(by='Total sales',ascending=False)
print('Payment Method Distribution:\n', PMD)

plt.figure(figsize=(8,5))
PM=sns.barplot(data=PMD,x=PMD['Payment_Method'],y=PMD['Total sales'],hue='Payment_Method',palette='viridis',legend=False)
plt.title('Payment Method Distribution by Total Sales')
plt.xlabel('Payment Method')
plt.ylabel('Total Sales')
for A in PM.containers:PM.bar_label(A,fmt='%.0f')
plt.show()

#Gender-wise Spending
GENDER_SPENDING=df.groupby(df['Gender'],as_index=False)['TotalPrice'].sum().sort_values(by='TotalPrice',ascending=False)
print('Gender-wise Spending:\n',GENDER_SPENDING)

plt.figure(figsize=(8,5))
GS=sns.barplot(data=GENDER_SPENDING,x=GENDER_SPENDING['Gender'],y=GENDER_SPENDING['TotalPrice'],hue='Gender',palette='viridis',legend=False)
plt.title('Gender-wise Spending')
plt.xlabel('Gender')
plt.ylabel('Total Spending')
for container in GS.containers:GS.bar_label(container,fmt='%.0f')
plt.show()

device_behavior=df.groupby('Gender')['Device_Type'].value_counts().reset_index()
print(device_behavior)

plt.figure(figsize=(10,6))
DB=sns.barplot(data=device_behavior,x='Gender',y='count',hue='Device_Type',palette='viridis')
plt.title('Gender-wise Device Usage')
plt.xlabel('Gender')
plt.ylabel('Count of Device Usage')
for container in DB.containers:DB.bar_label(container)
plt.show()

Top_5_Citis=(df.groupby('City',as_index=False)['Customer_ID'].count().sort_values(by='Customer_ID',ascending=False).head(5))
print('Top 5 Cities by Customer Count:\n', Top_5_Citis)

plt.figure(figsize=(10,6))
TC=sns.barplot(data=Top_5_Citis,x=Top_5_Citis['City'],y=Top_5_Citis['Customer_ID'],hue='City',palette='viridis',legend=False)
plt.title('Top 5 Cities by Customer Count')
plt.xlabel('City')
plt.ylabel('Number of Customers')
for container in TC.containers:TC.bar_label(container)
plt.show()

ms=df.groupby(df['Date'].dt.to_period('M'))['Total sales'].sum().nlargest(10)

plt.figure(figsize=(10,6))
MS=sns.barplot(data=ms.reset_index(),x='Date',y='Total sales',hue='Date',palette='magma',legend=False )
plt.title('Total Monthly Sales')
plt.xlabel('Date')
plt.ylabel('Total sales')
for container in MS.containers:MS.bar_label(container)

#Month name-wise Total Sales
MONTH_SALES=(df.groupby('Month',as_index=False)['Total sales'].sum())

plt.figure(figsize=(12,6))
MS=sns.barplot(data=MONTH_SALES,x='Month',y='Total sales',hue='Month',palette='viridis',legend=False)
plt.title('Month-wise Total Sales')
plt.xlabel('Month')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
for container in MS.containers:MS.bar_label(container)
plt.show()

df.info()

#Day-wise Sales
DAY_SALES=(df.groupby('Day_Name',as_index=False)['Total sales'].sum())

plt.figure(figsize=(10,6))
DS=sns.barplot(data=DAY_SALES,x='Day_Name',y='Total sales',hue='Day_Name',palette='magma',legend=False)
plt.title('Day-wise Total Sales')
plt.xlabel('Day')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
for container in DS.containers:DS.bar_label(container)
plt.show()

customer_spending=df.groupby('Customer_ID')['TotalPrice'].sum()
def segment(x):
    if x < 5000:
        return 'Low Spender'
    elif x < 15000:
        return 'Medium Spender'
    else:
        return 'High Spender'
customer_segments=customer_spending.apply(segment)
print(customer_segments.value_counts())

plt.figure(figsize=(8,5))
CSS=sns.countplot(x=customer_segments,palette='viridis',legend=False)
plt.title('Customer Segmentation by Spending')
plt.xlabel('Spending Segment')
plt.ylabel('Count')
for container in CSS.containers:CSS.bar_label(container)
plt.show()

AOV=df['TotalPrice'].sum()/df['Order_ID'].nunique()
print("Average Order Value:",round(AOV,2))

#Age Group-wise Sales
AGE_GROUP_SALES=(df.groupby('Age_Group',as_index=False)['Total sales'].sum())

plt.figure(figsize=(10,6))
AGS=sns.barplot(data=AGE_GROUP_SALES,x='Age_Group',y='Total sales',hue='Age_Group',palette='Set2',legend=False)
plt.title('Age Group-wise Total Sales')
plt.xlabel('Age Group')
plt.ylabel('Total Sales')
for container in AGS.containers:AGS.bar_label(container,fmt='%.0f')
plt.show()

"""#summary with key points

**Project Objective:**
*   To analyze customer behavior and sales patterns within an e-commerce dataset to derive actionable insights.

**Key Steps and Methodologies:**
1.  **Data Loading & Initial Assessment:** Loaded the dataset using pandas and performed initial checks for structure `(df.head(), df.info(), df.shape)` and missing values `(df.isnull().sum()).`
2.  **Data Cleaning & Preprocessing:**
*  Identified and dropped a fully null column `(Unnamed: 20)`
*   Converted the 'Date' column to a datetime format for time-series analysis.
*  Cleaned and transformed 'Discount_Percentage' from string to a numerical float.
*  Engineered a new feature,'TotalPrice', representing the
actual revenue after discount, and confirmed its accuracy compared to 'Total sales'.
3.  **Feature Engineering:** Created several new features to facilitate deeper analysis:
    *   'Month' and 'Day_Name' from the 'Date' column.
    *   'Age_Group' by categorizing the 'Age' column into bins.

4.  **Exploratory Data Analysis (EDA) & Visualization:** Extensively used `matplotlib` and `seaborn` to visualize and understand various aspects of the data:
*  **Product Performance:** Identified top 5 product categories by both total sales and quantity sold, revealing 'Electronics' as dominant in sales.
*  **Customer Analysis:**
    *   Profiled customer demographics by age, gender, and city.
    *   Identified Top 10 customers by spending.
    *   Performed customer segmentation based on 'TotalPrice' into 'Low Spender', 'Medium Spender', and 'High Spender' categories.
    *   Calculated the Average Order Value (AOV).
*  **Sales Trends:** Analyzed total monthly and day-wise sales, including monthly trends using `resample('ME')` (though commented out in the final cell, the intent was there, and a similar monthly plot was created).
*  **Payment & Device Usage:** Explored payment method distribution by total sales and gender-wise device usage, showing 'Credit Card' as the leading payment method and 'Mobile' as the primary device type.
*   **Geographic Insights:** Highlighted top cities by customer count.

**Key Insights Gained:**
*   Electronics, Home & Garden, and Sports are the highest revenue-generating product categories.

*   Customer spending varies significantly, with a large segment of 'Low Spenders' and a smaller, high-value 'High Spender' group.

*   Sales patterns can be observed across months and days of the week, indicating potential seasonality or peak periods.

*  Credit Card and Debit Card are the most popular payment methods, and mobile devices are predominantly used for e-commerce interactions.

*  Istanbul, Ankara, and Izmir are key cities with the highest customer bases.

##END OF PROJECT
"""